version: '1'

services:
  mysql:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: theusername
      MYSQL_PASSWORD: thepw
      MYSQL_DATABASE: mydb
    volumes:
      - ./data:/docker-entrypoint-initdb.d